---
:api_key: b9b2deef14e176983e1c1e7e2028f761
:password: a07ff797fbfa902a426a5c6b38019753
:store: wallsh.myshopify.com
:theme_id: 181728851
:whitelist_files:
- layout/
- assets/
- config/
- snippets/
- templates/
- locales/
